ktor:
  application:
    modules:
      - org.example.main.ApplicationKt.module

  deployment:
    port: 8085
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: password